# Generated by Django 4.1.4 on 2023-01-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_builder', '0002_menu_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
