# Generated by Django 4.1.4 on 2023-01-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_builder', '0003_remove_menu_slug_menu_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='URL'),
        ),
    ]
